#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : compat-goocanvas-soname2
Version  : 2.0.4
Release  : 22
URL      : https://download.gnome.org/sources/goocanvas/2.0/goocanvas-2.0.4.tar.xz
Source0  : https://download.gnome.org/sources/goocanvas/2.0/goocanvas-2.0.4.tar.xz
Summary  : A GTK+ canvas widget using cairo
Group    : Development/Tools
License  : LGPL-2.0
Requires: compat-goocanvas-soname2-lib = %{version}-%{release}
Requires: compat-goocanvas-soname2-license = %{version}-%{release}
Requires: compat-goocanvas-soname2-locales = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : glibc-bin
BuildRequires : gtk+-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libxslt-bin
BuildRequires : perl
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(pygobject-3.0)

%description
Welcome to GooCanvas
====================
(a cairo-based canvas widget for GTK+)

%package lib
Summary: lib components for the compat-goocanvas-soname2 package.
Group: Libraries
Requires: compat-goocanvas-soname2-license = %{version}-%{release}

%description lib
lib components for the compat-goocanvas-soname2 package.


%package license
Summary: license components for the compat-goocanvas-soname2 package.
Group: Default

%description license
license components for the compat-goocanvas-soname2 package.


%package locales
Summary: locales components for the compat-goocanvas-soname2 package.
Group: Default

%description locales
locales components for the compat-goocanvas-soname2 package.


%prep
%setup -q -n goocanvas-2.0.4
cd %{_builddir}/goocanvas-2.0.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1622832072
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1622832072
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-goocanvas-soname2
cp %{_builddir}/goocanvas-2.0.4/COPYING %{buildroot}/usr/share/package-licenses/compat-goocanvas-soname2/bf50bac24e7ec325dbb09c6b6c4dcc88a7d79e8f
%make_install
%find_lang goocanvas2
## Remove excluded files
rm -f %{buildroot}/usr/include/goocanvas-2.0/goocanvas.h
rm -f %{buildroot}/usr/include/goocanvas-2.0/goocanvasellipse.h
rm -f %{buildroot}/usr/include/goocanvas-2.0/goocanvasenumtypes.h
rm -f %{buildroot}/usr/include/goocanvas-2.0/goocanvasgrid.h
rm -f %{buildroot}/usr/include/goocanvas-2.0/goocanvasgroup.h
rm -f %{buildroot}/usr/include/goocanvas-2.0/goocanvasimage.h
rm -f %{buildroot}/usr/include/goocanvas-2.0/goocanvasitem.h
rm -f %{buildroot}/usr/include/goocanvas-2.0/goocanvasitemmodel.h
rm -f %{buildroot}/usr/include/goocanvas-2.0/goocanvasitemsimple.h
rm -f %{buildroot}/usr/include/goocanvas-2.0/goocanvasmarshal.h
rm -f %{buildroot}/usr/include/goocanvas-2.0/goocanvaspath.h
rm -f %{buildroot}/usr/include/goocanvas-2.0/goocanvaspolyline.h
rm -f %{buildroot}/usr/include/goocanvas-2.0/goocanvasrect.h
rm -f %{buildroot}/usr/include/goocanvas-2.0/goocanvasstyle.h
rm -f %{buildroot}/usr/include/goocanvas-2.0/goocanvastable.h
rm -f %{buildroot}/usr/include/goocanvas-2.0/goocanvastext.h
rm -f %{buildroot}/usr/include/goocanvas-2.0/goocanvasutils.h
rm -f %{buildroot}/usr/include/goocanvas-2.0/goocanvaswidget.h
rm -f %{buildroot}/usr/lib/python3.9/site-packages/gi/overrides/GooCanvas.py
rm -f %{buildroot}/usr/lib/python3.9/site-packages/gi/overrides/__pycache__/GooCanvas.cpython-39.pyc
rm -f %{buildroot}/usr/lib64/girepository-1.0/GooCanvas-2.0.typelib
rm -f %{buildroot}/usr/lib64/libgoocanvas-2.0.so
rm -f %{buildroot}/usr/lib64/pkgconfig/goocanvas-2.0.pc
rm -f %{buildroot}/usr/share/gir-1.0/GooCanvas-2.0.gir
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/GooCanvas.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/GooCanvasEllipse.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/GooCanvasEllipseModel.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/GooCanvasGrid.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/GooCanvasGridModel.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/GooCanvasGroup.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/GooCanvasGroupModel.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/GooCanvasImage.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/GooCanvasImageModel.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/GooCanvasItem.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/GooCanvasItemModel.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/GooCanvasItemModelSimple.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/GooCanvasItemSimple.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/GooCanvasPath.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/GooCanvasPathModel.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/GooCanvasPolyline.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/GooCanvasPolylineModel.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/GooCanvasRect.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/GooCanvasRectModel.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/GooCanvasStyle.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/GooCanvasTable.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/GooCanvasTableModel.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/GooCanvasText.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/GooCanvasTextModel.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/GooCanvasWidget.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/api-index-2.0.1.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/api-index-2.0.2.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/api-index-full.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/ch01.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/ch02.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/ch03.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/ch04.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/ch05.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/deprecated-api-index.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/goocanvas-architecture.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/goocanvas-coordinates.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/goocanvas-creating-items.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/goocanvas-model-view-canvas.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/goocanvas-overview.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/goocanvas-simple-canvas.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/goocanvas-wysiwyg.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/goocanvas2-GooCanvas-Types.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/goocanvas2.devhelp2
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/home.png
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/index.html
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/left-insensitive.png
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/left.png
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/right-insensitive.png
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/right.png
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/style.css
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/up-insensitive.png
rm -f %{buildroot}/usr/share/gtk-doc/html/goocanvas2/up.png

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgoocanvas-2.0.so.9
/usr/lib64/libgoocanvas-2.0.so.9.3.2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-goocanvas-soname2/bf50bac24e7ec325dbb09c6b6c4dcc88a7d79e8f

%files locales -f goocanvas2.lang
%defattr(-,root,root,-)

